service: sls-reflectify-api
frameworkVersion: "3"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x

functions:
  api:
    handler: dist/index.handler
    timeout: 99999
    events:
      - httpApi: "*"
